site_name: 运维成长之路
nav:
    - Home: index.md
    - 读书笔记:
        - 管理学: manager.md
        - 心理学: psychology.md
        - 组织行为学: organizational.md
    - 红帽认证:
        - RH124: rh124.md
        - RH134: rh134.md
        - RH254: rh254.md
    - 业界流行:
        - Ansible: ansible.md
        - Docker: docker.md
        - Python: python.md
        - Prometheus: prometheus.md
        - Kubernetes: kubernetes.md
    - 自动化部署:
        - 使用方法: db.md
        - 组件说明: comp.md
    - About:
      - 'License': 'license.md'
      - 'Release Notes': 'release-notes.md'
theme: readthedocs