site_name: 运维成长之路
nav:
    - Home: index.md
    - 读书笔记:
        - 管理学: manager.md
        - 心理学: psychology.md
        - 组织行为学: organizational.md
    - RHCE认证:
        - RH124: rh124.md
        - RH134: rh134.md
        - RH254: rh254.md
    - 阿里云认证:
        - ACA认证: aca.md
        - ACE认证: ace.md
        - ACP认证: acp.md
    - 业界流行:
        - Ansible: ansible.md
        - Docker: docker.md
        - Python: python.md
        - Prometheus: prometheus.md
        - Kubernetes: kubernetes.md
    - 自动化部署:
        - 数据库: db.md
        - 负载均衡: lb.md
        - 消息队列: index3.md
        - 存储系统: index4.md
        - 搜索服务: index4.md
        - 服务发现: index4.md
        - 应用服务器: index5.md
    - About:
      - 'License': 'license.md'
      - 'Release Notes': 'release-notes.md'
theme: readthedocs